pull_request_rules:
  - name: backport to maintained branches (v3, v3-ics, v4)
    conditions:
      - base=main
      - label!=dont_backport
    actions:
      backport:
        branches:
          - bp_test
        assignees: 
            - "{{ author }}"
        labels:
          - automerge
          - backport
        title: "[Backport #{{ number }} -> {{ base }}] {{ title }}"

  - name: automerge backported PR's for maintained branches (v3, v3-ics, v4)
    conditions:
      - label=automerge
      - base~=^(bp_test|bp_test2)$
    actions:
      merge:
        method: squash