backport_PR_rules:
  - name: backport to maintained branches (v3, v3-ics, v4)
    conditions:
      - base=main
      - label!=dont_backport
    actions:
      backport:
        branches:
          - bp_test
        assignees: {{author}}
        labels:
          - automerge
          - backport

automerge_backported_PRs:
  - name: automerge backported PR's for maintained branches (v3, v3-ics, v4)
    conditions:
      - label=automerge
      - or:
        base:
          - bp_test
    actions:
      merge:
        method: squash